sudo: required
language: java
install: true
services:
- docker
script:
- chmod +x gradlew
- "./gradlew build"

env:
  global:
  - secure: h10pvwZuItLUY0nHGyjR78WUtHHXmvfwtivkFmFe1FwNcR3e0MitXKkYvj3lVvldaYqAZ5QKx3OTUDca5KfrNGaGTTpZ3md7dXpBRRPbUxf5z6j6V3iy0ziBHb5PBuMXmm4ANivvANMgV6CXdMhziXhKSnW9yL9Wl+hvYhNhGP+BdPa+Go5yrh2JPkU0Z0F1ByVEMfLkR7v/9tr9wmmmqpWTZPJzJikqu3oGLLVSvnK3qmMK2XHm4O/FCnLWNDbtR+yPfE4othKpd/wkugO++FTB7idVKHgPnJx3WO/VXGkERj2dxVVXLZjJ2/RXUWKa9F7eWnkQq4MxPp/x7BYmreblB5WTaI6VNL8vYCWxVY52+N5/e619EwgKc3DXrusqK4Oc1cMhePWHBHxmNEubvLldYOuSCku2DOPctGHCzSwaatzOoRks+Id9xx2nbZIa5IXagerpmT0RdgObU7idoOyoXrI0ztXrZyhE1iRzc+ZHgsilroa6rXLqUZdyyG1J6F0af+q3KPm54fwP41x1vsuy6t/4iJxD14v0DFB5+RRCtID0jaJjdmOX3feHhE8cqxRSGIz6E/Xanj2CTvi/6byuzkheJyHM6V84xzPIun3qSLCI7L8G4uf2BshuXPlmuVgjfXgPHd2S1mqoj40pYbUc/ahZUs0lP6WqYYLbpbY=
  - secure: KvQZlU1aQ3SAy24V8gqxNnuv+f5/GuEVDQEbDNewUwsdRSnmS9Qdd5ydh4swR8IeM5uJm8757iZ/xZdEjK4lWJ8dbbEJlhJN5LBLG+0SK6BS49whFJEVPqZTCuuwW/k5Z/OqjLUDISL6hVOhbaMY7D9g9oQxIdyf2Ro+/qRAEXjZjlFoHMANchxdhOBAiQ4omqCoTXhSSGEFjF/ZtMz7c1F1Vwr7rUXT7zr+be+GkfOOV57FoEzJLa0hsnQA9kj2vrGqrVtay7JGlHloj0djj0UkHrRLyh+ADIpQIlY5vkouD6W9WHZeuEJWEbl/FLLxk1jDoWb1nq4ut36XBok5CLm5s/np96lFXXOKMHBGXx3VFmlBZnf56f6qosE2K0isaT6SmycrAaRKAJq6MqqHIOeIW1lSHAWAsYrYBU/un+ecMIRk5yGT+1GpbmiuHzb+mczS37Wg9Afop3ZwQNGiMxAjzyXNvoINZbqGJZWuAmtiKlU9u9kufJeBihvCkmv2IMZUQAGnUYAPfGVoBQIqOFpt5weWWv5exDEeb5OTFYIxL29xoFfnB5H+Bgf3tHgco2dTzqk7W+hIjjhzMl62OHk8ck2AAtKKG3UAZRRqj0CFxuk+M2FPnssDAdS2TXFx88MifdV4QyJX0IWlz7LzY0DP31xNk6QxdrAVKTGFUQQ=
